# Generated by Django 3.0 on 2020-01-17 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
