# Generated by Django 3.0 on 2019-12-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='description',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voting',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
