# Generated by Django 3.0.1 on 2019-12-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
