# Generated by Django 3.0.1 on 2019-12-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_voting', '0002_auto_20191228_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='is_one_choice',
            field=models.IntegerField(default=0),
        ),
    ]
