# Generated by Django 3.0 on 2019-12-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_voting', '0002_auto_20191220_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='author',
            field=models.IntegerField(null=True),
        ),
    ]
