# Generated by Django 3.0.1 on 2019-12-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_voting', '0002_auto_20191222_1445'),
        ('simple_voting', '0003_auto_20191222_0117'),
    ]

    operations = [
    ]
