# Generated by Django 3.0.1 on 2019-12-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_voting', '0003_voting_is_one_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='is_one_choice',
        ),
    ]
