# Generated by Django 3.0 on 2019-12-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_voting', '0004_auto_20191220_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='author',
            field=models.IntegerField(default=-1),
        ),
    ]
